import { useState } from "react";
import { Server, Database, Key, Loader2, Check, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { useIDEStore } from "@/lib/ide-store";
import type { BackendTemplate } from "@shared/schema";

const templates: Record<BackendTemplate, { name: string; icon: string; color: string }> = {
  firebase: { name: "Firebase", icon: "F", color: "text-amber-500" },
  supabase: { name: "Supabase", icon: "S", color: "text-green-500" },
};

export default function BackendWizard() {
  const { createFile } = useIDEStore();
  const [isOpen, setIsOpen] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<BackendTemplate>("firebase");
  const [config, setConfig] = useState({
    apiKey: "",
    projectId: "",
    authDomain: "",
    storageBucket: "",
    messagingSenderId: "",
    appId: "",
    // Supabase specific
    supabaseUrl: "",
    supabaseAnonKey: "",
  });
  const [generated, setGenerated] = useState<string | null>(null);
  const { toast } = useToast();

  const generateFirebaseConfig = () => {
    return `// Firebase configuration
// Generated by The Black Star Forge - Skeleton Key

import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

const firebaseConfig = {
  apiKey: "${config.apiKey}",
  authDomain: "${config.authDomain || `${config.projectId}.firebaseapp.com`}",
  projectId: "${config.projectId}",
  storageBucket: "${config.storageBucket || `${config.projectId}.appspot.com`}",
  messagingSenderId: "${config.messagingSenderId}",
  appId: "${config.appId}"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize services
export const auth = getAuth(app);
export const db = getFirestore(app);
export const storage = getStorage(app);

export default app;
`;
  };

  const generateSupabaseConfig = () => {
    return `// Supabase configuration
// Generated by The Black Star Forge - Skeleton Key

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = "${config.supabaseUrl}";
const supabaseAnonKey = "${config.supabaseAnonKey}";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Helper functions
export const signUp = async (email, password) => {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });
  return { data, error };
};

export const signIn = async (email, password) => {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });
  return { data, error };
};

export const signOut = async () => {
  const { error } = await supabase.auth.signOut();
  return { error };
};

export const getUser = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  return user;
};

export default supabase;
`;
  };

  const handleGenerate = () => {
    const configContent = selectedTemplate === "firebase" 
      ? generateFirebaseConfig() 
      : generateSupabaseConfig();
    
    setGenerated(configContent);
  };

  const handleAddToProject = () => {
    if (generated) {
      const fileName = selectedTemplate === "firebase" ? "firebase.js" : "supabase.js";
      createFile("/src", fileName, "file");
      
      // Note: In a real implementation, we'd also update the file content
      toast({
        title: "Backend added",
        description: `${templates[selectedTemplate].name} configuration file has been created`,
      });
      
      setIsOpen(false);
      setGenerated(null);
    }
  };

  const handleCopy = () => {
    if (generated) {
      navigator.clipboard.writeText(generated);
      toast({
        title: "Copied",
        description: "Configuration code copied to clipboard",
      });
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2" data-testid="button-backend-wizard">
          <Server className="w-4 h-4" />
          Add Backend
        </Button>
      </DialogTrigger>
      
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Key className="w-5 h-5 text-primary" />
            Skeleton Key - Backend Wizard
          </DialogTitle>
          <DialogDescription>
            Generate backend configuration files for Firebase or Supabase.
          </DialogDescription>
        </DialogHeader>

        <Tabs value={selectedTemplate} onValueChange={(v) => setSelectedTemplate(v as BackendTemplate)}>
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="firebase" data-testid="tab-firebase">
              <span className={templates.firebase.color}>{templates.firebase.icon}</span>
              <span className="ml-2">Firebase</span>
            </TabsTrigger>
            <TabsTrigger value="supabase" data-testid="tab-supabase">
              <span className={templates.supabase.color}>{templates.supabase.icon}</span>
              <span className="ml-2">Supabase</span>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="firebase" className="space-y-4 pt-4">
            <div className="grid gap-3">
              <div className="space-y-2">
                <Label htmlFor="firebase-api-key">API Key</Label>
                <Input
                  id="firebase-api-key"
                  type="password"
                  placeholder="AIza..."
                  value={config.apiKey}
                  onChange={(e) => setConfig({ ...config, apiKey: e.target.value })}
                  data-testid="input-firebase-api-key"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="firebase-project-id">Project ID</Label>
                <Input
                  id="firebase-project-id"
                  placeholder="my-project-12345"
                  value={config.projectId}
                  onChange={(e) => setConfig({ ...config, projectId: e.target.value })}
                  data-testid="input-firebase-project-id"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="firebase-app-id">App ID (optional)</Label>
                <Input
                  id="firebase-app-id"
                  placeholder="1:123456789:web:abc123"
                  value={config.appId}
                  onChange={(e) => setConfig({ ...config, appId: e.target.value })}
                  data-testid="input-firebase-app-id"
                />
              </div>
            </div>
          </TabsContent>

          <TabsContent value="supabase" className="space-y-4 pt-4">
            <div className="grid gap-3">
              <div className="space-y-2">
                <Label htmlFor="supabase-url">Supabase URL</Label>
                <Input
                  id="supabase-url"
                  placeholder="https://xxxxx.supabase.co"
                  value={config.supabaseUrl}
                  onChange={(e) => setConfig({ ...config, supabaseUrl: e.target.value })}
                  data-testid="input-supabase-url"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="supabase-anon-key">Anon Key</Label>
                <Input
                  id="supabase-anon-key"
                  type="password"
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  value={config.supabaseAnonKey}
                  onChange={(e) => setConfig({ ...config, supabaseAnonKey: e.target.value })}
                  data-testid="input-supabase-anon-key"
                />
              </div>
            </div>
          </TabsContent>
        </Tabs>

        {generated && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Generated Configuration</Label>
              <Button size="sm" variant="ghost" onClick={handleCopy} data-testid="button-copy-config">
                <Copy className="w-3 h-3 mr-1" />
                Copy
              </Button>
            </div>
            <Textarea
              readOnly
              value={generated}
              className="font-mono text-xs h-[200px]"
              data-testid="textarea-generated-config"
            />
          </div>
        )}

        <div className="flex justify-end gap-2 pt-2">
          {!generated ? (
            <Button onClick={handleGenerate} data-testid="button-generate-config">
              <Database className="w-4 h-4 mr-2" />
              Generate Config
            </Button>
          ) : (
            <Button onClick={handleAddToProject} data-testid="button-add-to-project">
              <Check className="w-4 h-4 mr-2" />
              Add to Project
            </Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
